name: Ubuntu-sanitizers

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # everyday at 2 am
    - cron:  '0 2 * * *'

jobs:
  build-ubuntu-sanitizers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flags: ["-fsanitize=address", "-fsanitize=leak", "-fsanitize=thread", "-fsanitize=undefined"]

    steps:
    # https://github.com/marketplace/actions/cancel-workflow-action
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print system information
      run: lscpu

    - name: Print OS information
      run: lsb_release -a

    - name: Install dependencies
      run: sudo apt-get install -y libx11-dev libdc1394-22-dev libv4l-dev liblapack-dev libopenblas-dev libeigen3-dev

    - name: Clone ViSP-images
      run: |
        git clone --depth 1 https://github.com/lagadic/ViSP-images ${HOME}/ViSP-images
        echo "VISP_INPUT_IMAGE_PATH=$HOME" >> $GITHUB_ENV
        echo ${VISP_INPUT_IMAGE_PATH}

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_C_FLAGS=${{ matrix.flags }} -DCMAKE_CXX_FLAGS=${{ matrix.flags }} -DCMAKE_LDFLAGS=${{ matrix.flags }} -DCMAKE_BUILD_TYPE=Debug
        cat ViSP-third-party.txt

    - name: Compile
      working-directory: build
      run: make -j2

    - name: Run unit tests with sanitizers
      working-directory: build
      run: ctest --output-on-failure
